import fs from "node:fs";
import path from "node:path";

type Adapter = (projectDir: string, installed: string[]) => void;

function ensure(dir: string) { fs.mkdirSync(dir, { recursive: true }); }

function instructions(projectDir: string, installed: string[]): string {
  const blocks: string[] = [
    "# Neo DevKit Generated Instructions",
    "",
    "This file is generated by Neo DevKit. Canonical source remains in `.devkit/`.",
    "",
    "## Installed Packs",
    ...installed.map(id => `- ${id}`),
    ""
  ];

  for (const id of installed) {
    const dir = path.join(projectDir, ".devkit", "packs", id, "instructions");
    if (!fs.existsSync(dir)) continue;
    for (const file of fs.readdirSync(dir).filter(f => f.endsWith(".md"))) {
      blocks.push(`## ${id}: ${file}`, "");
      blocks.push(fs.readFileSync(path.join(dir, file), "utf8").trim(), "");
    }
  }

  return blocks.join("\n");
}

function copyAgents(projectDir: string, installed: string[], target: string) {
  ensure(target);
  for (const id of installed) {
    const dir = path.join(projectDir, ".devkit", "packs", id, "agents");
    if (!fs.existsSync(dir)) continue;
    for (const file of fs.readdirSync(dir).filter(f => f.endsWith(".md"))) {
      fs.copyFileSync(path.join(dir, file), path.join(target, file));
    }
  }
}

function brainContext(projectDir: string): string {
  const generated = path.join(projectDir, ".devkit", "generated", "brain-context.md");
  if (!fs.existsSync(generated)) return "";
  return fs.readFileSync(generated, "utf8").trim();
}

function build(projectDir: string, installed: string[], provider: string): string {
  const parts = [instructions(projectDir, installed)];
  const brain = brainContext(projectDir);
  if (brain) parts.push("## Project Brain Context\n\n" + brain);
  parts.push(`\n<!-- Generated for ${provider}; do not edit as canonical source. -->`);
  return parts.join("\n\n") + "\n";
}

function copilot(projectDir: string, installed: string[]) {
  const dir = path.join(projectDir, ".github");
  ensure(dir);
  fs.writeFileSync(path.join(dir, "copilot-instructions.md"), build(projectDir, installed, "GitHub Copilot"));
  copyAgents(projectDir, installed, path.join(dir, "agents"));
}

function antigravity(projectDir: string, installed: string[]) {
  const dir = path.join(projectDir, ".gemini");
  ensure(dir);
  fs.writeFileSync(path.join(dir, "neo-devkit-instructions.md"), build(projectDir, installed, "Gemini / Antigravity"));
  copyAgents(projectDir, installed, path.join(dir, "agents"));
}

function claudeCode(projectDir: string, installed: string[]) {
  fs.writeFileSync(path.join(projectDir, "CLAUDE.md"), build(projectDir, installed, "Claude Code"));
  copyAgents(projectDir, installed, path.join(projectDir, ".claude", "agents"));
}

function cursor(projectDir: string, installed: string[]) {
  const dir = path.join(projectDir, ".cursor", "rules");
  ensure(dir);
  fs.writeFileSync(path.join(dir, "neo-devkit.mdc"), build(projectDir, installed, "Cursor"));
  copyAgents(projectDir, installed, path.join(projectDir, ".cursor", "agents"));
}

const ADAPTERS: Record<string, Adapter> = {
  copilot,
  antigravity,
  "claude-code": claudeCode,
  cursor
};

export function generateProviderArtifacts(projectDir: string, installed: string[], provider?: string) {
  const ids = provider ? [provider] : Object.keys(ADAPTERS);
  for (const id of ids) {
    const adapter = ADAPTERS[id];
    if (!adapter) throw new Error(`Unknown provider: ${id}`);
    adapter(projectDir, installed);
  }
}

export function supportedProviders(): string[] {
  return Object.keys(ADAPTERS);
}
